language: generic
branches:
  only:
  - master
cache:
  directories:
  - vendor
sudo: required
services:
- docker
install:
- make bootstrap
script:
- make test-cover build docker-build
before_deploy:
- make dist
deploy:
  provider: gcs
  access-key-id:
    secure: "MJ5qPDWHXcip6200yfFj4VYA4ONah67o5upit940R0grMRTihNaCij3uQWAoyH9LuXjcQcvcwvja75Zn7Ze7MDJt3WsvQ5iAfgg+kXcZBTLG5PQrtc6FlDBazdNpf2AZUVcJN7CWJZ+tyq4egHbOJu43mA3m0VKXlS+E6ARSz7IWruyrYCcZUmlIQmuzc5a3zANjLRo1tsBjSukdENhlcuFAe3GU2n3LkJSxBLjJKUJOYpM3kHNQuF/bchAUd2XQk9QbrS17NnmxmTCpI4Fa3n0efAk3mDVfIIqZtPs2Oeb2N/Xmkpp03Lk+TDTqoxSMp7EgPjofA1FupY+EapIBUiyjnovCxKgMQtCkcZibBiUt51VnCTlW4fqYPStAPmI2WAj/ZiPrhjDxg2omdWcOfvpN3TCg0qa7VGq0w43LUlp4iPm2mwO8kelPW6Wt27FdmOEdH9RzEjWqJ7lXvbfVMCcsymXA1+09R/mxyJTwCIHD08HlCIrSuVc/wcLuAsNijKufdrFeb5B59Jcosp+Hx1ByEI9a28EOvbQrvnRub9mr5s+disRPvYXPpacJ6bh6tXKtnc++cYdkIoSHfa7vDR1pV+Mr9BS8A9n0VT5qIoGeIGKZVPxX7GbhawpRTu63OlfpCXzmdA/3pcptf4AK6RuMJ4gLWMop0iPwupBi+7U="
  secret-access-key:
    secure: "Ziv9gyXPssv9aeMhPnLHn1uM+g6sJAh0Xkv8eKuQVzyNrn7FwNZp2qd41bU8gcbIfbxcLc3+s1t1+4eJKHp93AniALBQkPm170EJo78u/dsd6y/0OngqR0P/EinsVX7B7vBW1u/8h4ueeSylFRmASwfKlJUHiQfuI5AOvVKQx9xC0PotLiNFBJP55NJ/Gq2GlERBZS3Q+ReNPiCBPDxEBu263bKfhYCZAN6WlXFt9ujgaSk1/2FyCId1GBpinz8ZnAl3bfgykrSdBSfMU8fVVKFHXTWf5DL+04+WswE2I+Wg7B7MGFNIr5x6wbttWmIvJg1cWMalnxt7jFY/+gOUBT1v3lE/+D2BiNI2vZr7Sv6yBVIYjE7SDboGkQp0L38i519k9rhlg8pKV2IfSIfT9BdArnmRjzJYqaiSaahS1q1AUTtXFAY9u+hk3/2jL+iEVq6qT+1/JDyQavv8OL1sw+MJ+FIyz+95z1N9EB0do+0VyOhaJqeq5FR4itLIxyBWODJ26KALVrPDZl3SmgScwE0XVhlgJ6WkcQ9Ua+Y0jDpXkLC+iEE1LVy1OVwIR2XReZleeXJJzvTfcIKpCxtWkAJwBOZZUWdqXoNNZVdrZXsupdzho7Mg34eJ3IqCFoROP7wRjM7fF5dZxJ1GqHtgumBipD9b0ldEjYQrQxjfiY4="
  bucket: k8s-claimer
  local-dir: _dist
  on:
    branch: master
  acl: public-read

after_success:
  - bash <(curl -s https://codecov.io/bash
