language: generic
branches:
  only:
  - master
cache:
  directories:
  - vendor
sudo: required
services:
- docker
install:
- make bootstrap
script:
- make build test docker-build
before_deploy:
- make dist
deploy:
  provider: gcs
  access-key-id:
  secret-access-key:
  bucket: k8s-claimer
  local-dir: _dist
  on:
    branch: master
  acl: public-read
